import express from "express";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const app = express();

const PORT = 5111;
const __dirname = dirname(fileURLToPath(import.meta.url));

// when you put "default-src 'self'" all third party urls will be blocked (for image , script, css etc), only internal urls would be allowed
// script-src = only script from internal domain are allowed , script from http://unsecure.com is allowed
// unsafe-inline = makes sure that the inline script tag in html is executed, if not give no inline script would be executed
// nonce = unique random value generated by the server and added to inline script. The unique value is not read by anyone,
// this makes sure that only the valid script are read, while injected ones are not executed

app.use((req, res, next) => {
  res.setHeader(
    "Content-Security-Policy",
    "default-src 'self';" +
      "script-src 'self' 'unsafe-inline' 'http://unsecure.com'",
  );
  next();
});

app.get("/", (req, res) => {
  res.sendFile(join(__dirname, "index.html"));
});

app.listen(PORT, () => {
  console.log(`App is listening at ${PORT}`);
});
